# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
    - linux
    - osx
julia:
    - 1.0
    - 1.1
    - 1.2
    - 1.3
    - nightly
notifications:
    email: false

after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  include:
    - stage: Documentation
      julia: 1.3
      script: julia --project=docs -e '
          using Pkg;
          Pkg.add(PackageSpec(url="https://github.com/TotalVerb/SchemeSyntax.jl"));
          Pkg.develop(PackageSpec(name="SchemeSyntax", uuid="ae6fee66-c21b-11e9-21f5-f142c7f3686e"));
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
